#ifndef __OUTPUTCONSTANTS_H
#define __OUTPUTCONSTANTS_H

#define NO_IMPULSO 0
#define IMPULSO 1
#define CONDUCCION 2
#define BLOQUEO 3
#define QRS 4
#define BLOQUEO_RAMA_DERECHA 5
#define BLOQUEO_RAMA_IZQUIERDA 6
#define INICIO_ONDA_P 7
#define FIN_ONDA_P 8
#define ONDA_QRS 9
#define FALLA_RAMA_DERECHA 10
#define FALLA_RAMA_IZQUIERDA 11
#define IMPULSO_INICIAL 12
#define IMPULSO_NO_PRODUCIDO 13
#define IMPULSO_ANOMALO 14

#endif